[package]
name = "imagism"
version = "0.1.0"
authors = ["Zack Corr <zack@z0w0.me>"]
edition = "2018"

[profile.dev]
opt-level = 1

[lib]
name = "imagism"
path = "src/lib.rs"
crate-type = ["dylib"]

[dependencies]
rustler = "0.21.1"
rustler_codegen = "0.21.1"
image = "0.23.7"